### PR TITLE
Forwarded cout during run to a log file in outputs/logs

### PR DESCRIPTION
**Pull request by kzscisoft**
SCRC-94 Save log outputs as part of model run. 
The solution was to create a new class that acts as a wrapper around an `ostream` and sends the output to a text file as well as the terminal. This has been added to `Utilities.h` as `logging_stream`.

`Model.cpp` now creates a folder `logs` in the `outputs` directory and places log files with the name format:

`run_nPars-<no. of parameters>_seedMethod-<seeding method>_ExecAt-<time script was executed>.log`

### CODE REVIEW

**Comment by kzscisoft** [comment]
If I have only the output directory as an argument for `logging_stream` then we will lose the information about the seed etc. Are you sure that is ok? @peter-t-fox

**Comment by peter-t-fox** [comment]
@kzscisoft Okay, I didn't notice that. But that leads me to this question: is there a reason why you want that information in the log file name? Isn't that information is already captured in the contents of the log file itself?

**Comment by kzscisoft** [comment]
@peter-t-fox It was more for quick external reference but if you think that is not an issue then it makes life easier not including it.

**Comment by peter-t-fox** [comment]
@kzscisoft I think it's okay without it.

**Comment by kzscisoft** [comment]
@peter-t-fox All those changes should now be in there

**Comment by kzscisoft** [comment]
This should now be merged after https://github.com/ScottishCovidResponse/Covid19_EERAModel/pull/18

**Pull request merged**
