### PR TITLE
Added break statement to prevent looping when not necessary

### PR DESCRIPTION
**Pull request by kzscisoft**
"SCRC-91: Simulation continues looping even when max number of accepted particles reached"

### CODE REVIEW

**Comment by thibaud-porphyre** [comment]
This is normal behaviour. The model was coded that way originally in order to parallelise the code using openMP. Using openMP, it is my understanding that break statement is not good standard and will not be allowed. It is also the reason why there is a ``abort`` statement.

**Comment by artemis-beta** [comment]
@thibaud-porphyre I guess we can therefore close SCRC-91 if that’s the reason?

**Comment by kzscisoft** [comment]
@thibaud-porphyre In that case should SCRC-91 be closed as this is not an issue but rather a requirement?

**Comment by thibaud-porphyre** [comment]
@kzscisoft yes, you are correct. Thanks for pointing that out.

**Pull request closed without merging**
